import type {
  Achievement,
  WeeklyProgress,
  WeightEntry,
  Meal,
  Exercise,
} from "@/lib/types";

export const motivationalQuotes = [
  "Every step counts. You're doing great! 👏",
  "Small progress is still progress. Keep going! 💪",
  "Your future self will thank you for today's effort 🌟",
  "It's not about perfect, it's about effort ✨",
  "You're stronger than you think. One more rep! 🔥",
  "Movement is medicine for the body and soul 💚",
  "Today's workout is tomorrow's strength 🏋️",
  "The only bad workout is the one that didn't happen ✅",
  "Believe in yourself and all that you are 🌈",
  "Stay consistent. Results will follow 📈",
];

export const sampleAchievements: Achievement[] = [
  {
    id: "first_workout",
    name: "First Steps",
    description: "Complete your first workout",
    icon: "🏃",
    progress: 100,
    unlockedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "streak_3",
    name: "Hot Streak",
    description: "3-day activity streak",
    icon: "🔥",
    progress: 100,
    unlockedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "streak_7",
    name: "Weekly Warrior",
    description: "7-day activity streak",
    icon: "⚔️",
    progress: 71,
  },
  {
    id: "steps_10k",
    name: "10K Club",
    description: "Hit 10,000 steps in one day",
    icon: "👟",
    progress: 100,
    unlockedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "calories_500",
    name: "Calorie Crusher",
    description: "Burn 500+ calories in a workout",
    icon: "💥",
    progress: 64,
  },
  {
    id: "water_8",
    name: "Hydration Hero",
    description: "Drink 8 glasses of water in a day",
    icon: "💧",
    progress: 62,
  },
  {
    id: "workout_30min",
    name: "Half Hour Power",
    description: "30+ minute workout session",
    icon: "⏱️",
    progress: 100,
    unlockedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "streak_14",
    name: "Fortnight Force",
    description: "14-day activity streak",
    icon: "⭐",
    progress: 35,
  },
];

export const sampleWeeklyProgress: WeeklyProgress[] = [
  { day: "Mon", steps: 7200, calories: 1950, activeMinutes: 38 },
  { day: "Tue", steps: 8900, calories: 2100, activeMinutes: 52 },
  { day: "Wed", steps: 6100, calories: 1780, activeMinutes: 25 },
  { day: "Thu", steps: 9500, calories: 2250, activeMinutes: 60 },
  { day: "Fri", steps: 7800, calories: 2050, activeMinutes: 42 },
  { day: "Sat", steps: 10200, calories: 2400, activeMinutes: 75 },
  { day: "Sun", steps: 4500, calories: 1650, activeMinutes: 15 },
];

export const sampleWeightEntries: WeightEntry[] = [
  { date: "Week 1", weight: 82.5 },
  { date: "Week 2", weight: 82.1 },
  { date: "Week 3", weight: 81.8 },
  { date: "Week 4", weight: 81.3 },
  { date: "Week 5", weight: 81.0 },
  { date: "Week 6", weight: 80.7 },
  { date: "Week 7", weight: 80.4 },
  { date: "Week 8", weight: 80.2 },
];

export const sampleMeals: Meal[] = [
  {
    id: "m1",
    type: "breakfast",
    name: "Oatmeal with berries",
    calories: 320,
    protein: 12,
    carbs: 55,
    fat: 8,
    time: "7:30 AM",
  },
  {
    id: "m2",
    type: "lunch",
    name: "Grilled chicken salad",
    calories: 450,
    protein: 38,
    carbs: 20,
    fat: 22,
    time: "12:15 PM",
  },
  {
    id: "m3",
    type: "snack",
    name: "Greek yogurt + nuts",
    calories: 200,
    protein: 15,
    carbs: 12,
    fat: 10,
    time: "3:30 PM",
  },
  {
    id: "m4",
    type: "dinner",
    name: "Salmon with quinoa",
    calories: 520,
    protein: 42,
    carbs: 45,
    fat: 18,
    time: "7:00 PM",
  },
];

export const exerciseLibrary: Exercise[] = [
  {
    id: "pushups",
    name: "Push-ups",
    category: "strength",
    targetMuscles: ["Chest", "Shoulders", "Triceps"],
    instructions: [
      "Start in plank position, hands shoulder-width apart",
      "Lower body until chest nearly touches floor",
      "Push back up to starting position",
      "Keep core tight throughout",
    ],
    sets: 3,
    reps: 12,
    restTime: 60,
  },
  {
    id: "squats",
    name: "Bodyweight Squats",
    category: "strength",
    targetMuscles: ["Quadriceps", "Hamstrings", "Glutes"],
    instructions: [
      "Stand with feet shoulder-width apart",
      "Bend knees and lower hips like sitting in chair",
      "Keep chest up and back straight",
      "Return to standing position",
    ],
    sets: 3,
    reps: 15,
    restTime: 60,
  },
  {
    id: "lunges",
    name: "Walking Lunges",
    category: "strength",
    targetMuscles: ["Quadriceps", "Glutes", "Hamstrings"],
    instructions: [
      "Step forward with right leg",
      "Lower until both knees at 90 degrees",
      "Push off to bring left leg forward",
      "Alternate legs, keep torso upright",
    ],
    sets: 3,
    reps: 10,
    restTime: 45,
  },
  {
    id: "plank",
    name: "Plank Hold",
    category: "strength",
    targetMuscles: ["Core", "Shoulders", "Back"],
    instructions: [
      "Start on forearms and toes",
      "Keep body in straight line",
      "Engage core and glutes",
      "Hold position without sagging",
    ],
    duration: 45,
    restTime: 30,
  },
  {
    id: "jumping_jacks",
    name: "Jumping Jacks",
    category: "cardio",
    targetMuscles: ["Full Body"],
    instructions: [
      "Stand with feet together, arms at sides",
      "Jump feet apart while raising arms overhead",
      "Jump back to starting position",
      "Maintain steady rhythm",
    ],
    duration: 60,
    restTime: 30,
  },
  {
    id: "mountain_climbers",
    name: "Mountain Climbers",
    category: "cardio",
    targetMuscles: ["Core", "Shoulders", "Hip Flexors"],
    instructions: [
      "Start in plank position",
      "Drive right knee toward chest",
      "Quickly switch to left knee",
      "Maintain fast alternating pace",
    ],
    duration: 45,
    restTime: 30,
  },
  {
    id: "bicycle_crunches",
    name: "Bicycle Crunches",
    category: "strength",
    targetMuscles: ["Abdominals", "Obliques"],
    instructions: [
      "Lie on back, hands behind head",
      "Lift shoulders, bring right elbow to left knee",
      "Switch sides in pedaling motion",
      "Keep lower back pressed to floor",
    ],
    sets: 3,
    reps: 20,
    restTime: 45,
  },
  {
    id: "burpees",
    name: "Burpees",
    category: "hiit",
    targetMuscles: ["Full Body", "Cardio"],
    instructions: [
      "Start standing, drop to squat position",
      "Kick feet back to plank",
      "Do one push-up",
      "Jump feet forward and explosively jump up",
    ],
    sets: 3,
    reps: 10,
    restTime: 90,
  },
  {
    id: "downward_dog",
    name: "Downward Dog",
    category: "yoga",
    targetMuscles: ["Hamstrings", "Shoulders", "Back"],
    instructions: [
      "Start on hands and knees",
      "Lift hips toward ceiling, straighten legs",
      "Press heels toward floor",
      "Hold for 5 deep breaths",
    ],
    duration: 60,
    restTime: 15,
  },
  {
    id: "warrior_pose",
    name: "Warrior II Pose",
    category: "yoga",
    targetMuscles: ["Legs", "Core", "Shoulders"],
    instructions: [
      "Stand with feet wide apart",
      "Turn right foot out 90 degrees",
      "Bend right knee over ankle",
      "Extend arms parallel to floor, gaze over right hand",
    ],
    duration: 45,
    restTime: 15,
  },
  {
    id: "high_knees",
    name: "High Knees",
    category: "cardio",
    targetMuscles: ["Hip Flexors", "Quadriceps", "Core"],
    instructions: [
      "Stand tall, run in place",
      "Drive knees up toward chest",
      "Pump arms for momentum",
      "Keep quick, light foot contacts",
    ],
    duration: 45,
    restTime: 30,
  },
  {
    id: "glute_bridges",
    name: "Glute Bridges",
    category: "strength",
    targetMuscles: ["Glutes", "Hamstrings", "Lower Back"],
    instructions: [
      "Lie on back, knees bent, feet flat",
      "Push through heels to lift hips",
      "Squeeze glutes at top",
      "Lower with control",
    ],
    sets: 3,
    reps: 15,
    restTime: 45,
  },
];
